#pragma once
#define MAX_FILE_NAME 200
#define MAX_FILE_TITLE 50
#define MAX_TAG_LENGTH 50
#define MAX_TAG_COUNT  32
#define MAX_OPEN_FILE_COUNT 20
#define FONT_SIZE 15
#define MAX_CLIPBOARD_COPY 1000

